name: Build LaTeX document
on:
   workflow_dispatch:
   push:
     paths:
       - '_latex/**'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          working_directory: _latex
          latexmk_use_xelatex: true
      - name: Commit PDF
        id: commit
        run: |
          mv _latex/cv.pdf assets/pdf/cv.pdf
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/pdf/cv.pdf
          git commit -m "[bot] updated resume.pdf"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}